version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - NODE_ENV=development
    restart: unless-stopped 