version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "8090:80"
    volumes:
      - ${VOLUMES:-./frontend:/usr/share/nginx/html}
      - ${NGINX_CONF:-./nginx.conf}:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 