# ModAgents Docker Compose Configuration
# Usage: docker-compose up

services:
  # Core Agent System Service
  agent-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: mod-agents:latest
    container_name: mod-agents
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - AGENT_MODE=${AGENT_MODE:-production}
      - REDIS_URL=redis://redis:6379
      - ENABLE_METRICS=${ENABLE_METRICS:-false}
    volumes:
      # Mount source code for development
      - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: mod-agents-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: mod-agents-network
    driver: bridge

# Configuration:
# - Basic deployment: docker-compose up
# - Includes: agent-system + redis
# - Access API at: http://localhost:8000