global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent-library'
    static_configs:
      - targets: ['orchestrator:8000', 'translation-agent:8001', 'nlp-analyzer:8002', 'enneagram-agent:8003']
    metrics_path: /metrics
    scrape_interval: 5s